#!/bin/sh
# example script for resetting the eiger logging database

mysql -u root -proot << EOF
drop database capp ;
create database capp ;
use capp;
source /home/eric/eiger/trunk/database/schema.sql
quit
EOF
