#!/bin/sh
# parameter study for simple example
#
# job control
ulimit -s unlimited
nproc="8"
for np in $nproc; do
for n in 10 1000 100000 100000000; do
name="cxxapp_fake.$n"
mkdir dumps.$name
cd dumps.$name
#export PERF_APPEND=0
echo  "`date`  $np ../cxxapp_fake $name"
mpirun.openmpi -np $np ../cxxapp_fake <<EOF > pmd.$name.log
$n
EOF
date
mkdir text
mv tesla.*.log text
cd ..
done ; # n
done ; # np
