#!/bin/sh
# example script for resetting the eiger logging database

mysql -u root -peiger123 << EOF
drop database cxxapp ;
drop database capp ;
drop database fortapp ;
create database capp ;
create database fortapp ;
create database cxxapp ;
use capp;
source /home/baallan/sst/gatech/eiger-svn/database/schema.sql
use cxxapp;
source /home/baallan/sst/gatech/eiger-svn/database/schema.sql
use fortapp;
source /home/baallan/sst/gatech/eiger-svn/database/schema.sql
quit
EOF
